language: ruby
rvm:
  - 2.2
  - jruby # 1.9
env:
  - RAILS_VERSION="~> 5.0.7.2"
  - RAILS_VERSION="~> 4.1.1"
  - RAILS_VERSION="~> 4.0.5"
  - RAILS_VERSION="~> 3.2.18"
  - RAILS_VERSION="~> 3.0.20"
matrix:
  exclude:
    - rvm: 1.8.7
      env: RAILS_VERSION="~> 4.0.5"
    - rvm: 1.8.7
      env: RAILS_VERSION="~> 4.1.1"
    - rvm: 2.1
      env: RAILS_VERSION="~> 2.2.3"
    - rvm: 2.1
      env: RAILS_VERSION="~> 2.3.18"
    - rvm: jruby
      env: RAILS_VERSION="~> 2.2.3"
